Feature/virtual item
Phobossus/RPPluginsEngine pull request #211
Opened 2021-04-15 21:04 UTC by Pedrokase

2021-04-20 18:00 UTC, Phobossus requested changes

2021-04-20 18:00 UTC, Phobossus commented on RP-Core/src/main/java/customItems/controller/ItemController.java
> +public class ItemController {
Looks ok although I'd probably refactor the shit out of it :D

2021-04-20 18:06 UTC, Pedrokase commented on RP-Core/src/main/java/customItems/CustomItemFactory.java
> +            persistentValue(CustomItemNamespace.REMOVE_ON_DROP, Boolean.toString(true));
Agree. But for simplicity in a first phase, I'm always removing on death.
Later versions can perhaps have the item persist on death?

2021-04-29 09:12 UTC, Phobossus approved these changes

2021-05-01 14:46 UTC, merged