Feature/inventory controller
Phobossus/RPPluginsEngine pull request #213
Opened 2021-04-25 11:16 UTC by Pedrokase

2021-05-02 10:30 UTC, Phobossus requested changes

2021-05-02 10:30 UTC, Phobossus commented on RP-Core/src/main/java/main/utils/inventory/InventoryController.java
> +        if (savedInventories.containsKey(uniqueId)) {
Should we throw exception here or just log it and return? Are we handling it somehow?

2021-05-02 10:31 UTC, Pedrokase commented on RP-Core/src/main/java/main/utils/inventory/InventoryController.java
> +        if (savedInventories.containsKey(uniqueId)) {
Good point, I'll just log it

2021-05-05 09:18 UTC, Phobossus requested changes

2021-05-05 09:18 UTC, Phobossus commented on RP-Core/src/main/java/main/utils/inventory/InventoryController.java
> +    private final Map<UUID, Inventory> savedInventories = new HashMap<>();
Maps.newConcurrentMap()

2021-05-19 18:22 UTC, Phobossus requested changes

2021-05-19 18:22 UTC, Phobossus commented on RP-Core/src/main/java/main/utils/inventory/InventoryController.java
> +            event.getItem().remove();
Did you test if this doesn't remove the just received item?

2021-05-19 18:22 UTC, Phobossus commented on RP-Core/src/main/java/main/utils/inventory/VirtualCharacterEquipment.java
> +
throw new NotImplementedException() for every unimplemented method, although the 'non-silent' standard set methods for boots,head,leggings,chest could probably be implemented just as fast.

2021-05-19 18:22 UTC, Phobossus commented on RP-Core/src/main/java/main/utils/inventory/VirtualCharacterInventory.java
> +        return Arrays.stream(virtualInventory).anyMatch(item -> item.getType().equals(itemStack.getType()) && item.getAmount() == itemStack.getAmount());
Just making sure - comparing both material and stacks is how bukkit does it too?

2021-05-19 18:22 UTC, Phobossus commented on RP-Core/src/main/java/main/utils/inventory/VirtualCharacterInventory.java
> +    public void remove(@NotNull Material material) throws IllegalArgumentException {
Reason for why the remove methods are not implemented?

2021-05-19 18:22 UTC, Pedrokase commented on RP-Core/src/main/java/main/utils/armor/ArmorUtils.java
> +    public static final EnumSet<Material> BOOT_TAG = EnumSet.of(LEATHER_BOOTS, GOLDEN_BOOTS, IRON_BOOTS, DIAMOND_BOOTS, NETHERITE_BOOTS);
Good catch

2021-05-19 18:26 UTC, Pedrokase commented on RP-Core/src/main/java/abilitiesV2/utils/ItemUtils.java
> +            if (EntityType.FOX.equals(entity.getType())) slot = EquipmentSlot.HAND;
Without it, the code will attempt to equip armor to the fox, which might lead to unknown side-effects

2021-05-19 18:31 UTC, Pedrokase commented on RP-Core/src/main/java/abilitiesV2/utils/ItemUtils.java
> +            if (EntityType.FOX.equals(entity.getType())) slot = EquipmentSlot.HAND;
Ah, right. When I coded this I was falsely under the assumption that it would only be called by "EntityPickupEvent". I have to rethink this method

2021-05-19 18:39 UTC, Pedrokase commented on RP-Core/src/main/java/main/utils/inventory/InventoryController.java
> +            event.getItem().remove();
I did, yes. The Item in this case does not refer to `ItemStack`, but `Item` which is an Entity. 
(Fun fact, if you do not cancel the event, it still gives you the item - even if you removed it)

2021-05-19 18:40 UTC, Pedrokase commented on RP-Core/src/main/java/main/utils/inventory/VirtualCharacterEquipment.java
> +
I have no idea what the noise is, hence why I didn't want to implement it. 
I'll change it to the throw alternative

2021-05-19 18:45 UTC, Pedrokase commented on RP-Core/src/main/java/main/utils/inventory/VirtualCharacterInventory.java
> +        return Arrays.stream(virtualInventory).anyMatch(item -> item.getType().equals(itemStack.getType()) && item.getAmount() == itemStack.getAmount());
![image](https://user-images.githubusercontent.com/32021527/118867215-bd1b5b00-b8da-11eb-856e-7677fb312690.png)

2021-05-19 18:46 UTC, Pedrokase commented on RP-Core/src/main/java/main/utils/inventory/VirtualCharacterInventory.java
> +    public void remove(@NotNull Material material) throws IllegalArgumentException {
Probably out of laziness. Lemme implement them now

2021-05-30 17:54 UTC, merged